/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef TAXES_LIBRARY_H
#define TAXES_LIBRARY_H

#ifdef _WIN32
#define TAXES_LIBRARY_EXPORT_FUNC __declspec(dllexport)
#else
#define TAXES_LIBRARY_EXPORT_FUNC
#endif

#include <string>
#include <vector>
#include "shoppingitem.h"

void printInputItem(ShoppingItem item);
void printOutputItem(ShoppingItem item);
void printTestInput(std::vector<ShoppingItem> listItems, std::string testName);
void TAXES_LIBRARY_EXPORT_FUNC ext_executeTest(std::vector<ShoppingItem> listItems, std::string testName );

#endif
